apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flink-app-1
  description: Flink Test application
  labels:
    component: Flink
spec:
  type: library
  lifecycle: production
  owner: fms
  system: fms
  # dependsOn:
  #   - resource:default/artists-db
  # providesApis:
  #   - artist-api

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: flink-app-1-events
  description: Events API for Flink App 1
spec:
  type: asyncapi
  lifecycle: production
  owner: fms
  system: fms
  definition: |
  asyncapi: 3.0.0
  info:
    title: Flink App 1
    version: '1.0.0'
    description: |
      Flink Test application
  servers:
    mosquitto:
      host: test.mosquitto.org
      protocol: mqtt
  channels:
    lightMeasured:
      address: 'light/measured'
      messages:
        lightMeasuredMessage:
          name: LightMeasured
          payload:
            type: object
            properties:
              id:
                type: integer
                minimum: 0
                description: ID of the streetlight.
              lumens:
                type: integer
                minimum: 0
                description: Light intensity measured in lumens.
              sentAt:
                type: string
                format: date-time
                description: Date and time when the message was sent.
  operations:
    onLightMeasured:
      action: 'receive'
      summary: Information about environmental lighting conditions for a particular streetlight.
      channel:
        $ref: '#/channels/lightMeasured'